name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  AFTER_BUILD: |
    echo 'a'
    echo 'b'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ env.AFTER_BUILD }}"
